os:
  - linux
language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
python:
#  - 3.7  
  - 3.8
install:
  - export CC=gcc-9 && export CXX=g++-9
  - python -c "from sysconfig import get_paths as gp; print(gp()[\"include\"])"
  - ${CXX} --version
  - (cd azulbot/azulsimcpp && make)
  - pip install numpy numba
  - pip install coverage
script:
  - coverage run -m unittest test_azulpy
  - coverage run -a -m unittest test_azulsim
after_success:
  - bash <(curl -s https://codecov.io/bash)
