os:
  - linux
language: python
python:
  - 3.7
  - 3.8
install:
  - pip install numpy numba
  - pip install coverage
script:
  - coverage run -m unittest test_azul
#  - coverage run -a -m unittest tests.utils_test
after_success:
  - bash <(curl -s https://codecov.io/bash)