os:
  - linux
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-9
  - CC=gcc-9 && CXX=g++-9
language: python
python:
  - 3.7
  - 3.8
install:
  - pip install numpy numba pybind11
  - pip install coverage
  - pip install -e .
script:
  - coverage run -m unittest test_azulpy
  - coverage run -a -m unittest test_azulsim
after_success:
  - bash <(curl -s https://codecov.io/bash)